configuration: Release
branches:
  only:
    - master
environment:
  COVERALLS_REPO_TOKEN:
    secure: nnLizSCRAP0VMS3MwoIOJqEW7NXo9vNeM
before_build:
  - nuget restore Httwrap.sln

build:
  project: Httwrap.sln       
  verbosity: minimal
  
test_script:
  - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[Coveralls*]*" -target:packages\NUnit.Runners.2.6.4\tools\nunit-console.exe -targetargs:"/noshadow /domain:single /framework:net-4.5 Httwrap.Tests\bin\%CONFIGURATION%\Httwrap.Tests.dll" -filter:"+[Httwrap]* -[Httwrap.Tests]*" -output:coverage.xml

after_test:
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r nnLizSCRAP0VMS3MwoIOJqEW7NXo9vNeM
