configuration: Release
branches:
  only:
    - master
environment:
  COVERALLS_REPO_TOKEN:
    secure: nnLizSCRAP0VMS3MwoIOJqEW7NXo9vNeM
before_build:
  - nuget restore Httwrap.sln

build:
  project: Httwrap.sln       
  verbosity: minimal

#test:
#  assemblies:
#    - '**\*.Tests.dll'
test_script:
- ps: >-
    .\packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -target:.\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe -register:user "-targetargs:""Httwrap.Tests\bin\$env:CONFIGURATION\Httwrap.Tests.dll"" /framework:net-4.5 /noshadow" -filter:"+[Httwrap*]*" -output:opencoverCoverage.xml
    
#    Get-Content '.\opencoverCoverage.xml'
    
    .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
